### ISSUE TITLE
Publishing site fails

### ISSUE THREAD

**Issue by rossabaker** [typelevel/unique#182]
```
Run eval "$$(ssh-agent -s)"
/home/runner/work/_temp/a264b0e7-6ea6-49bd-8835-12f2ce647af5.sh: eval: line 1: syntax error near unexpected token `ssh-agent'
Error: Process completed with exit code 2.
```

Good first issue for a Distinguished YAML Engineer.  I think it's just escaped wrong.

**Comment by VlachJosef** [comment]
I think `ssh-agent` is not needed since this build uses `GitHub4s` for microsite publishing 🤔

**Comment by rossabaker** [comment]
Oh, that might be true. Let's remove it, and I can do a manual publish.

**Comment by rossabaker** [comment]
Well, manually publishing it won't test the yaml.  We'll have a new release with Scala 3.0.0-final later this month to be sure.
